services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    environment:
      - MSSQL_SA_PASSWORD=Password@1
      - ACCEPT_EULA=Y
    platform: linux/amd64
    ports:
      - 1433:1433